name:                gourmet
version:             0.1.0.0
github:              "strangeglyph/gourmet"
license:             BSD3
author:              "Lia Schütze"
maintainer:          "mail@strangegly.ph"
copyright:           "2021 Lia Schütze"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gourmet#readme>

dependencies:
- base >= 4.7 && < 5
- text
- yesod
- req
- feed

library:
  source-dirs: src

executables:
  gourmet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gourmet

tests:
  gourmet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gourmet
